apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  annotations:
    kube-ci.qutics.com/cacheScope: project
    kube-ci.qutics.com/cacheSize: 20Gi
  creationTimestamp: null
spec:
  arguments: {}
  entrypoint: test
  templates:
  - inputs: {}
    metadata: {}
    name: test
    outputs: {}
    steps:
    - - arguments: {}
        name: test
        template: test-node
  - container:
      args:
      - sh
      - -c
      - |
        set -x
        set -e
        gofmt -l -e .
        go vet .
        go run honnef.co/go/tools/cmd/staticcheck .
        go test -v
      command:
      - /bin/sh
      - -c
      env:
      - name: GOPROXY
        value: http://gomod-athens:8080
      image: golang:1.18
      name: ""
      resources: {}
      volumeMounts:
      - mountPath: /cache
        name: build-cache
      workingDir: /src
    inputs:
      artifacts:
      - git:
          repo: '{{workflow.parameters.repo}}'
          revision: '{{workflow.parameters.revision}}'
        name: code
        path: /src
    metadata: {}
    name: test-node
    outputs: {}
  volumes:
  - name: build-cache
    persistentVolumeClaim:
      claimName: '{{workflow.parameters.cacheVolumeClaimName}}'
status:
  finishedAt: null
  startedAt: null
