tolerations:
- effect:  "NoSchedule"
  key:     "dedicated"
  value:   "ci"

nodeSelector:
  jenkins: "true"

templates:
  baton:
    description: Uses baton to build an image, and to deploy
    ci: /config/templates/baton-ci.yml
    deploy: /config/templates/baton-deploy.yml
