tolerations:
- effect:  "NoSchedule"
  key:     "dedicated"
  value:   "ci"

nodeSelector:
  ci: "true"

templates:
  baton:
    description: Uses docker to build images from repos
    ci: /config/docker-ci.yaml

cacheDefaults:
  storageClassName: standard-new

buildBranches: ".+"
buildDraftPRs: false
